#!/usr/bin/env php
<?php

namespace frame\core;

use frame\core\console\Console;

error_reporting(E_ALL ^ E_NOTICE);
date_default_timezone_set('PRC');
define('ROOT_PATH', __DIR__);

// 版本限制
if (version_compare(PHP_VERSION, '7.0.0', '<')) {
    throw new \Exception('php version must greater than or equal 7.0.0');
}

// 加载公共函数
require ROOT_PATH . '/app/common/helper/helper.php';
// app初始化，自动载入类文件
require ROOT_PATH . '/frame/core/App.php';
App::consoleInit();

App::getContainer()->resolve(Console::class)->run();